# required
[[plugins]]
repo = 'Shougo/dein.vim'

# molokaiのカラーテーマ"
[[plugins]]
repo = 'tomasr/molokai'

# monokaiのカラーテーマ"
[[plugins]]
repo = 'crusoexia/vim-monokai'

# コメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'

# 複数行をまとめてコメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

# ステータスバーをいい感じにする
[[plugins]]
repo = 'vim-airline/vim-airline'

# テーマ集
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# 様々な言語のシンタックスとインデント調整
[[plugins]]
repo = 'sheerun/vim-polyglot'

# 対となる括弧を消してくれる
[[plugins]]
repo = 'jiangmiao/auto-pairs'
[[plugins]]
repo = 'tpope/vim-endwise'

# インデントなどの統一
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# カラースキーム選択
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'ujihisa/unite-colorscheme'

# インデント可視化
[[plugins]]
repo = 'mxw/vim-jsx'

# コード補完
# [[plugins]]
# repo = 'Valloric/YouCompleteMe'

# マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# ヘルプの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# 置換のプレビュー
[[plugins]]
repo = 'markonm/traces.vim'

# 自動補完
[[plugins]]
repo = 'Shougo/neocomplete.vim'
# スニペットの補完機能
[[plugins]]
repo = 'Shougo/neosnippet'
# スニペット集
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'violetyk/neocomplete-php.vim'

# Vueシンタックスハイライト
[[plugins]]
repo = 'posva/vim-vue'

# js syntax
[[plugins]]
repo = 'pangloss/vim-javascript'
[[plugins]]
repo = 'crusoexia/vim-javascript-lib'

# ts syntax
[[plugins]]
repo = 'herringtondarkholme/yats.vim'

# dart syntax
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

# jsx syntax
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

# ヤンクする場所をハイライト
[[plugins]]
repo = 'machakann/vim-highlightedyank'

# インデントの可視化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# gruvbox
[[plugins]]
repo = 'morhetz/gruvbox'

# Git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# HTML補完
[[plugins]]
repo = 'mattn/emmet-vim'

# コード検索が楽ちん
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/unite-outline'

# 画面サイズ調整
[[plugins]]
repo = 'simeji/winresizer'

# Git操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# markdown review
[[plugins]]
repo = 'skanehira/preview-markdown.vim'

# js整形
[[plugins]]
repo = 'maksimr/vim-jsbeautify'

